name: quran
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  pull_to_refresh: ^1.6.1
  progress_indicators: ^0.1.5
  google_fonts_arabic: ^1.1.7
  geolocator: ^5.2.1
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  url_launcher: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # image png
    - asset/pic/bg_picture.png
    - asset/pic/pp_profil.jpg
    - asset/pic/instagram.png
    - asset/pic/facebook.png
    - asset/pic/whatsapp.png
    - asset/pic/github.png
  # image surat
    - asset/surat/sname_1.png
    - asset/surat/sname_2.png
    - asset/surat/sname_3.png
    - asset/surat/sname_4.png
    - asset/surat/sname_5.png
    - asset/surat/sname_6.png
    - asset/surat/sname_7.png
    - asset/surat/sname_8.png
    - asset/surat/sname_9.png
    - asset/surat/sname_10.png
    - asset/surat/sname_11.png
    - asset/surat/sname_12.png
    - asset/surat/sname_13.png
    - asset/surat/sname_14.png
    - asset/surat/sname_15.png
    - asset/surat/sname_16.png
    - asset/surat/sname_17.png
    - asset/surat/sname_18.png
    - asset/surat/sname_19.png
    - asset/surat/sname_20.png
    - asset/surat/sname_21.png
    - asset/surat/sname_22.png
    - asset/surat/sname_23.png
    - asset/surat/sname_24.png
    - asset/surat/sname_25.png
    - asset/surat/sname_26.png
    - asset/surat/sname_27.png
    - asset/surat/sname_28.png
    - asset/surat/sname_29.png
    - asset/surat/sname_30.png
    - asset/surat/sname_31.png
    - asset/surat/sname_32.png
    - asset/surat/sname_33.png
    - asset/surat/sname_34.png
    - asset/surat/sname_35.png
    - asset/surat/sname_36.png
    - asset/surat/sname_37.png
    - asset/surat/sname_38.png
    - asset/surat/sname_39.png
    - asset/surat/sname_40.png
    - asset/surat/sname_41.png
    - asset/surat/sname_42.png
    - asset/surat/sname_43.png
    - asset/surat/sname_44.png
    - asset/surat/sname_45.png
    - asset/surat/sname_46.png
    - asset/surat/sname_47.png
    - asset/surat/sname_48.png
    - asset/surat/sname_49.png
    - asset/surat/sname_50.png
    - asset/surat/sname_51.png
    - asset/surat/sname_52.png
    - asset/surat/sname_53.png
    - asset/surat/sname_54.png
    - asset/surat/sname_55.png
    - asset/surat/sname_56.png
    - asset/surat/sname_57.png
    - asset/surat/sname_58.png
    - asset/surat/sname_59.png
    - asset/surat/sname_60.png
    - asset/surat/sname_61.png
    - asset/surat/sname_62.png
    - asset/surat/sname_63.png
    - asset/surat/sname_64.png
    - asset/surat/sname_65.png
    - asset/surat/sname_66.png
    - asset/surat/sname_67.png
    - asset/surat/sname_68.png
    - asset/surat/sname_69.png
    - asset/surat/sname_70.png
    - asset/surat/sname_71.png
    - asset/surat/sname_72.png
    - asset/surat/sname_73.png
    - asset/surat/sname_74.png
    - asset/surat/sname_75.png
    - asset/surat/sname_76.png
    - asset/surat/sname_77.png
    - asset/surat/sname_78.png
    - asset/surat/sname_79.png
    - asset/surat/sname_80.png
    - asset/surat/sname_81.png
    - asset/surat/sname_82.png
    - asset/surat/sname_83.png
    - asset/surat/sname_84.png
    - asset/surat/sname_85.png
    - asset/surat/sname_86.png
    - asset/surat/sname_87.png
    - asset/surat/sname_88.png
    - asset/surat/sname_89.png
    - asset/surat/sname_90.png
    - asset/surat/sname_91.png
    - asset/surat/sname_92.png
    - asset/surat/sname_93.png
    - asset/surat/sname_94.png
    - asset/surat/sname_95.png
    - asset/surat/sname_96.png
    - asset/surat/sname_97.png
    - asset/surat/sname_98.png
    - asset/surat/sname_99.png
    - asset/surat/sname_100.png
    - asset/surat/sname_101.png
    - asset/surat/sname_102.png
    - asset/surat/sname_103.png
    - asset/surat/sname_104.png
    - asset/surat/sname_105.png
    - asset/surat/sname_106.png
    - asset/surat/sname_107.png
    - asset/surat/sname_108.png
    - asset/surat/sname_109.png
    - asset/surat/sname_110.png
    - asset/surat/sname_111.png
    - asset/surat/sname_112.png
    - asset/surat/sname_113.png
    - asset/surat/sname_114.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial
      fonts:
        - asset: asset/font/arial.ttf
        - weight: 400
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
